---
apiVersion: v1
kind: Service
metadata:
  name: "jpoode-sec-svc"
  labels:
    app: "jpoode-sec"
spec:
  ports:
  - port: 8090
    name: "ode-sec-server" 
  clusterIP: "None" 
  selector:
    app: "jpoode-sec"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "jpoode-sec"
  labels:
    app: "jpoode-sec"
spec:
  replicas: {{ .Values.replicas.jpoode_sec }}
  selector:
    matchLabels:
      app: "jpoode-sec"
  template:
    metadata:
      labels:
        app: "jpoode-sec"
    spec:
      containers:
      - name: "jpoode-sec-image-sha256-1"
        image: "{{ .Values.images.jpoode_sec.repository }}:{{ .Values.images.jpoode_sec.tag }}" 
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.25"
        tty: true
        stdin: true